### ISSUE TITLE
`Unhandled error: {:error, :checkout_failure}` on OTP 24.3 when publishing firmware

### ISSUE THREAD

**Issue by jjcarstens** [nerves-hub/nerves_hub_user_api#32]
Looks like OTP 24.3 broke pooling in hackney, which is the underlying adapter of `Tesla`, which is the HTTP library used here.

See https://github.com/benoitc/hackney/issues/689#issuecomment-1066169694 (which may or may not be related in fixing)

**Comment by fhunleth** [comment]
It looks like this is fixed in OTP 24.3.1.

**Comment by jjcarstens** [comment]
Sure is. Just confirmed
